On same deadline, items queued first have priority
Smithay/calloop pull request #205
Opened 2024-07-31 05:19 UTC by amcandio

When multiple are registered at the same time, those registered first should have priority to make scheduling behavior easier to predict. I don't think this should be added as documented behavior to prevent users from depending on it.

2024-08-10 16:15 UTC, notgull commented
@amcandio Please rebase on `master` to fix the CI

2024-08-12 19:47 UTC, amcandio commented
@notgull rebased!

2024-08-20 18:23 UTC, amcandio commented
@notgull any update on this?

2024-08-22 03:11 UTC, notgull requested changes
Apologies, I was distracted.

2024-08-22 03:11 UTC, notgull commented on src/sources/timer.rs
> +        // earlier values have priority, on same deadline items queued first have priority
Please use proper capitalization and punctuation for comments.

2025-05-13 12:10 UTC, amcandio commented
@notgull apologies for the delay!

2025-07-29 08:33 UTC, amcandio commented
Hi! Any chance we can ship this one? Not super important but I have this old tech debt item that I could close with this feature!

2025-09-10 05:44 UTC, closed without merging