refactor: Simplify timeout calculation in Poll::poll()
Smithay/calloop pull request #214
Opened 2024-11-20 17:19 UTC by kenoss

Refactor using `Instant::saturating_duration_since()` and `Option::or()`.

2024-11-20 20:12 UTC, notgull requested changes

2024-11-20 20:12 UTC, notgull commented on src/sys.rs
> +        let timeout2 = self
Change this name to "next_timeout"

2024-11-21 16:06 UTC, kenoss commented on src/sys.rs
> +        let timeout2 = self
Thanks! Done.

2024-11-21 20:13 UTC, notgull approved these changes

2024-11-21 20:14 UTC, merged